# Generated by Django 5.2.6 on 2025-10-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability_slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslots',
            name='name',
            field=models.CharField(choices=[('office', 'Work / Office'), ('remote', 'Work from home'), ('study', 'Study'), ('break', 'Free Time'), ('meeting', 'Meeting'), ('travel', 'Travel')], max_length=100),
        ),
    ]
