# Generated by Django 5.2.6 on 2025-10-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(choices=[('ZoneInfo', 'ZoneInfo'), ('reset_tzpath', 'reset_tzpath'), ('available_timezones', 'available_timezones'), ('TZPATH', 'TZPATH'), ('ZoneInfoNotFoundError', 'ZoneInfoNotFoundError'), ('InvalidTZPathWarning', 'InvalidTZPathWarning')], default='UTC', max_length=50),
        ),
    ]
