# Generated by Django 5.2.6 on 2025-10-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='timezone',
        ),
    ]
